var assetData = {
	tree: [
		[41, 65],
		[
			[0, 2],
			[200, 340],
			[83, 70],
			[283, 70],
		],
	],

	bench_dark: [
		[46, 64],
		[
			[18, 326],
			[120, 230],
		],
	],

	flower_bush_white: [
		[28, 28],
		[
			[283, 35],
			[130, 135],
		],
	],

	flower_bush_yellow: [
		[28, 28],
		[
			[300, 300],
			[238, 53],
			[103, 153],
		],
	],
};

var pfpData = [
	// { url: "AKHIL BVS", premium: true, type: "ethmaxi" },
	// { url: "Anish Mohammed" },
	// { url: "Bhavnaaaaa" },
	// { url: "Eemis" },
	// { url: "harshitbeni" },
	// { url: "Keith Salins" },
	// { url: "KIRAN V K" },
	// { url: "Meeeeeth" },
	// { url: "Neo" },
	// { url: "nickk.jr" },
	// { url: "Nimki" },
	// { url: "OxMubzz" },
	// { url: "PNJBI" },
	// { url: "Sai Rithwik M" },
	// { url: "Sanjana" },
	// { url: "Ulyana" },
	// { url: "Shryasss" },
	// { url: "Sidd" },
	// { url: "Yugesh" },
	// { url: "amansharma2910" },
	// { url: "Nayan Choudhary" },
	// { url: "Akash Jaiswal" },
	// { url: "Anshul" },
	// { url: "Adhiraj Singh" },
	// { url: "Sanjeed" },
	// { url: "Hacker" },

	// { url: "Archana" },
	// { url: "Aadi" },
	// { url: "ALI J" },
	// { url: "Anish De" },
	// { url: "Ankita" },
	// { url: "anoushk.sol" },
	// { url: "beingwayne.eth" },
	// { url: "Deepso" },
	// { url: "DrhVu" },
	// { url: "GC" },
	// { url: "Hariharan" },
	// { url: "immutbl" },
	// { url: "Kishore Amruth" },
	// { url: "notlazykid" },
	// { url: "r4reetik" },
	// { url: "Santosh" },
	// { url: "Upkaran" },
	// { url: "Vandini" },

	// { url: "Ankita2" },
	// { url: "harsh.eth" },
	// { url: "KUSH RATNA", premium: true, type: "space" },
	// { url: "Sumxxt" },
	// { url: "Vipra" },

	// { url: "0xatharva7" },
	// { url: "0xBhadresh.eth" },
	// { url: "abheek.eth" },
	// { url: "AK" },
	// { url: "Arushi" },
	// { url: "Ashh" },
	// { url: "Ashi" },
	// { url: "chandra bose" },
	// { url: "Crons" },
	// { url: "CryptoBABU" },
	// { url: "Ethmemoir" },
	// { url: "Gautam Hegde" },
	// { url: "Guru Hegde" },
	// { url: "Harshajny" },
	// { url: "Heemank Verma" },
	// { url: "Karan", premium: true, type: "ethmaxi" },
	// { url: "Mitul Gajera" },
	// { url: "mxxnwolf" },
	// { url: "Phantom" },
	// { url: "Priyanshu Ratnakar" },
	// { url: "pxvvxn" },
	{ url: "Robin" },
	{ url: "Sagnik Sahoo" },
	{ url: "Sarvagna" },
	{ url: "Sixel" },
	{ url: "Sudeep" },
	{ url: "syruponpixels" },
	{ url: "Zebra" },
	{ url: "zeXX" },
];
